version: "3.7"

services:
  #webapp:
  #  ports:
  #  - "8080:80"
  #  image: prj2testimage:latest
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile.fe
  db:
    image: postgres
    ports: 
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: devpassword
      POSTGRES_USER: superpank
      POSTGRES_DB: pankdb
  backend:
    image: prj2testmigrations:latest
    ports:
      - "4000:3000"
    links:
      - db:db
    environment:
      POSTGRES_URI: jdbc:postgresql://db:5432/pankdb
      PGRST_DB_URI: postgres://superpank:devpassword@db:5432/pankdb
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon #In production this role should not be the same as the one used for the connection
      POSTGRES_PASSWORD: devpassword
      POSTGRES_USER: superpank
      POSTGRES_DB: pankdb
    build:
      context: ./
      dockerfile: Dockerfile.be
    depends_on: 
    - db
