name: prod

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: echo Running build!
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build web app
      run: |
        npm install
        npm run build
    - name: Send to Azure
      run: |
        az acr login --name $acr_registry
        docker build --file Dockerfile.fe --tag $acr_login/pank_webapp:v1 .
        docker build --file Dockerfile.be --tag $acr_login/pank_migrations:v1 .
        docker push $acr_login/pank_webapp:v1
        docker push $acr_login/pank_migrations:v1
        az acr repository list --name $acr_registry --output table
      env:
        acr_registry: ${{secrets.AZURE_ACR_REGISTRY}}
        acr_login: ${{secrets.AZURE_ACR_LOGIN_SERVER}}

