name: Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run frontend build
      run: |
        ls 
        npm install
        npm run build
    - name: Run frontend tests
      run: |
        npm run test
      env:
        CI: true
    - name: Run backend migrations
      run: |
        docker network create testnetwork
        docker build --file Dockerfile.db --tag temporarypankdbs:v1 .
        docker build --file Dockerfile.migrate --tag temporarypankmigrations:v1 .
        docker run --name temppostgres -e POSTGRES_PASSWORD=testpass --network testnetwork -p 5432:5432 --detach temporarypankdbs:v1
        sleep 20
        docker run --network testnetwork temporarypankmigrations:v1
        docker stop temppostgres
